/* Generated by scripts/build-locale-index.ts – do not edit. One directory per language: locales/<id>/*.json */
import ar_banner from './ar/banner.json';
import ar_chrome from './ar/chrome.json';
import ar_howto from './ar/howto.json';
import ar_legal from './ar/legal.json';
import ar_nav from './ar/nav.json';
import ar_pages from './ar/pages.json';
import ar_sections from './ar/sections.json';
import ar_ui from './ar/ui.json';
import ar_widget from './ar/widget.json';
import cn_banner from './cn/banner.json';
import cn_chrome from './cn/chrome.json';
import cn_howto from './cn/howto.json';
import cn_legal from './cn/legal.json';
import cn_nav from './cn/nav.json';
import cn_pages from './cn/pages.json';
import cn_sections from './cn/sections.json';
import cn_ui from './cn/ui.json';
import cn_widget from './cn/widget.json';
import cs_banner from './cs/banner.json';
import cs_chrome from './cs/chrome.json';
import cs_nav from './cs/nav.json';
import cs_pages from './cs/pages.json';
import cs_sections from './cs/sections.json';
import cs_ui from './cs/ui.json';
import cs_widget from './cs/widget.json';
import da_banner from './da/banner.json';
import da_chrome from './da/chrome.json';
import da_nav from './da/nav.json';
import da_pages from './da/pages.json';
import da_sections from './da/sections.json';
import da_ui from './da/ui.json';
import da_widget from './da/widget.json';
import de_banner from './de/banner.json';
import de_chrome from './de/chrome.json';
import de_howto from './de/howto.json';
import de_legal from './de/legal.json';
import de_nav from './de/nav.json';
import de_pages from './de/pages.json';
import de_sections from './de/sections.json';
import de_ui from './de/ui.json';
import de_widget from './de/widget.json';
import el_banner from './el/banner.json';
import el_chrome from './el/chrome.json';
import el_nav from './el/nav.json';
import el_pages from './el/pages.json';
import el_sections from './el/sections.json';
import el_ui from './el/ui.json';
import el_widget from './el/widget.json';
import en_banner from './en/banner.json';
import en_chrome from './en/chrome.json';
import en_nav from './en/nav.json';
import en_pages from './en/pages.json';
import en_ui from './en/ui.json';
import en_widget from './en/widget.json';
import es_banner from './es/banner.json';
import es_chrome from './es/chrome.json';
import es_howto from './es/howto.json';
import es_legal from './es/legal.json';
import es_nav from './es/nav.json';
import es_pages from './es/pages.json';
import es_sections from './es/sections.json';
import es_ui from './es/ui.json';
import es_widget from './es/widget.json';
import fi_banner from './fi/banner.json';
import fi_chrome from './fi/chrome.json';
import fi_nav from './fi/nav.json';
import fi_pages from './fi/pages.json';
import fi_sections from './fi/sections.json';
import fi_ui from './fi/ui.json';
import fi_widget from './fi/widget.json';
import fr_banner from './fr/banner.json';
import fr_chrome from './fr/chrome.json';
import fr_howto from './fr/howto.json';
import fr_legal from './fr/legal.json';
import fr_nav from './fr/nav.json';
import fr_pages from './fr/pages.json';
import fr_sections from './fr/sections.json';
import fr_ui from './fr/ui.json';
import fr_widget from './fr/widget.json';
import he_banner from './he/banner.json';
import he_chrome from './he/chrome.json';
import he_nav from './he/nav.json';
import he_pages from './he/pages.json';
import he_sections from './he/sections.json';
import he_ui from './he/ui.json';
import he_widget from './he/widget.json';
import hu_banner from './hu/banner.json';
import hu_chrome from './hu/chrome.json';
import hu_nav from './hu/nav.json';
import hu_pages from './hu/pages.json';
import hu_sections from './hu/sections.json';
import hu_ui from './hu/ui.json';
import hu_widget from './hu/widget.json';
import id_banner from './id/banner.json';
import id_chrome from './id/chrome.json';
import id_nav from './id/nav.json';
import id_pages from './id/pages.json';
import id_sections from './id/sections.json';
import id_ui from './id/ui.json';
import id_widget from './id/widget.json';
import it_banner from './it/banner.json';
import it_chrome from './it/chrome.json';
import it_howto from './it/howto.json';
import it_legal from './it/legal.json';
import it_nav from './it/nav.json';
import it_pages from './it/pages.json';
import it_sections from './it/sections.json';
import it_ui from './it/ui.json';
import it_widget from './it/widget.json';
import ja_banner from './ja/banner.json';
import ja_chrome from './ja/chrome.json';
import ja_nav from './ja/nav.json';
import ja_pages from './ja/pages.json';
import ja_sections from './ja/sections.json';
import ja_ui from './ja/ui.json';
import ja_widget from './ja/widget.json';
import ko_banner from './ko/banner.json';
import ko_chrome from './ko/chrome.json';
import ko_nav from './ko/nav.json';
import ko_pages from './ko/pages.json';
import ko_sections from './ko/sections.json';
import ko_ui from './ko/ui.json';
import ko_widget from './ko/widget.json';
import nl_banner from './nl/banner.json';
import nl_chrome from './nl/chrome.json';
import nl_nav from './nl/nav.json';
import nl_pages from './nl/pages.json';
import nl_sections from './nl/sections.json';
import nl_ui from './nl/ui.json';
import nl_widget from './nl/widget.json';
import no_banner from './no/banner.json';
import no_chrome from './no/chrome.json';
import no_nav from './no/nav.json';
import no_pages from './no/pages.json';
import no_sections from './no/sections.json';
import no_ui from './no/ui.json';
import no_widget from './no/widget.json';
import pl_banner from './pl/banner.json';
import pl_chrome from './pl/chrome.json';
import pl_nav from './pl/nav.json';
import pl_pages from './pl/pages.json';
import pl_sections from './pl/sections.json';
import pl_ui from './pl/ui.json';
import pl_widget from './pl/widget.json';
import pt_banner from './pt/banner.json';
import pt_chrome from './pt/chrome.json';
import pt_howto from './pt/howto.json';
import pt_legal from './pt/legal.json';
import pt_nav from './pt/nav.json';
import pt_pages from './pt/pages.json';
import pt_sections from './pt/sections.json';
import pt_ui from './pt/ui.json';
import pt_widget from './pt/widget.json';
import ru_banner from './ru/banner.json';
import ru_chrome from './ru/chrome.json';
import ru_howto from './ru/howto.json';
import ru_legal from './ru/legal.json';
import ru_nav from './ru/nav.json';
import ru_pages from './ru/pages.json';
import ru_sections from './ru/sections.json';
import ru_ui from './ru/ui.json';
import ru_widget from './ru/widget.json';
import sv_banner from './sv/banner.json';
import sv_chrome from './sv/chrome.json';
import sv_nav from './sv/nav.json';
import sv_pages from './sv/pages.json';
import sv_sections from './sv/sections.json';
import sv_ui from './sv/ui.json';
import sv_widget from './sv/widget.json';
import th_banner from './th/banner.json';
import th_chrome from './th/chrome.json';
import th_nav from './th/nav.json';
import th_pages from './th/pages.json';
import th_sections from './th/sections.json';
import th_ui from './th/ui.json';
import th_widget from './th/widget.json';
import tr_banner from './tr/banner.json';
import tr_chrome from './tr/chrome.json';
import tr_nav from './tr/nav.json';
import tr_pages from './tr/pages.json';
import tr_sections from './tr/sections.json';
import tr_ui from './tr/ui.json';
import tr_widget from './tr/widget.json';
import tw_banner from './tw/banner.json';
import tw_chrome from './tw/chrome.json';
import tw_nav from './tw/nav.json';
import tw_pages from './tw/pages.json';
import tw_sections from './tw/sections.json';
import tw_ui from './tw/ui.json';
import tw_widget from './tw/widget.json';
import ur_banner from './ur/banner.json';
import ur_chrome from './ur/chrome.json';
import ur_nav from './ur/nav.json';
import ur_pages from './ur/pages.json';
import ur_sections from './ur/sections.json';
import ur_ui from './ur/ui.json';
import ur_widget from './ur/widget.json';
import vi_banner from './vi/banner.json';
import vi_chrome from './vi/chrome.json';
import vi_nav from './vi/nav.json';
import vi_pages from './vi/pages.json';
import vi_sections from './vi/sections.json';
import vi_ui from './vi/ui.json';
import vi_widget from './vi/widget.json';

export const LOCALE_DATA: Record<string, Record<string, unknown>> = {
  ar: { banner: ar_banner, chrome: ar_chrome, howto: ar_howto, legal: ar_legal, nav: ar_nav, pages: ar_pages, sections: ar_sections, ui: ar_ui, widget: ar_widget },
  cn: { banner: cn_banner, chrome: cn_chrome, howto: cn_howto, legal: cn_legal, nav: cn_nav, pages: cn_pages, sections: cn_sections, ui: cn_ui, widget: cn_widget },
  cs: { banner: cs_banner, chrome: cs_chrome, nav: cs_nav, pages: cs_pages, sections: cs_sections, ui: cs_ui, widget: cs_widget },
  da: { banner: da_banner, chrome: da_chrome, nav: da_nav, pages: da_pages, sections: da_sections, ui: da_ui, widget: da_widget },
  de: { banner: de_banner, chrome: de_chrome, howto: de_howto, legal: de_legal, nav: de_nav, pages: de_pages, sections: de_sections, ui: de_ui, widget: de_widget },
  el: { banner: el_banner, chrome: el_chrome, nav: el_nav, pages: el_pages, sections: el_sections, ui: el_ui, widget: el_widget },
  en: { banner: en_banner, chrome: en_chrome, nav: en_nav, pages: en_pages, ui: en_ui, widget: en_widget },
  es: { banner: es_banner, chrome: es_chrome, howto: es_howto, legal: es_legal, nav: es_nav, pages: es_pages, sections: es_sections, ui: es_ui, widget: es_widget },
  fi: { banner: fi_banner, chrome: fi_chrome, nav: fi_nav, pages: fi_pages, sections: fi_sections, ui: fi_ui, widget: fi_widget },
  fr: { banner: fr_banner, chrome: fr_chrome, howto: fr_howto, legal: fr_legal, nav: fr_nav, pages: fr_pages, sections: fr_sections, ui: fr_ui, widget: fr_widget },
  he: { banner: he_banner, chrome: he_chrome, nav: he_nav, pages: he_pages, sections: he_sections, ui: he_ui, widget: he_widget },
  hu: { banner: hu_banner, chrome: hu_chrome, nav: hu_nav, pages: hu_pages, sections: hu_sections, ui: hu_ui, widget: hu_widget },
  id: { banner: id_banner, chrome: id_chrome, nav: id_nav, pages: id_pages, sections: id_sections, ui: id_ui, widget: id_widget },
  it: { banner: it_banner, chrome: it_chrome, howto: it_howto, legal: it_legal, nav: it_nav, pages: it_pages, sections: it_sections, ui: it_ui, widget: it_widget },
  ja: { banner: ja_banner, chrome: ja_chrome, nav: ja_nav, pages: ja_pages, sections: ja_sections, ui: ja_ui, widget: ja_widget },
  ko: { banner: ko_banner, chrome: ko_chrome, nav: ko_nav, pages: ko_pages, sections: ko_sections, ui: ko_ui, widget: ko_widget },
  nl: { banner: nl_banner, chrome: nl_chrome, nav: nl_nav, pages: nl_pages, sections: nl_sections, ui: nl_ui, widget: nl_widget },
  no: { banner: no_banner, chrome: no_chrome, nav: no_nav, pages: no_pages, sections: no_sections, ui: no_ui, widget: no_widget },
  pl: { banner: pl_banner, chrome: pl_chrome, nav: pl_nav, pages: pl_pages, sections: pl_sections, ui: pl_ui, widget: pl_widget },
  pt: { banner: pt_banner, chrome: pt_chrome, howto: pt_howto, legal: pt_legal, nav: pt_nav, pages: pt_pages, sections: pt_sections, ui: pt_ui, widget: pt_widget },
  ru: { banner: ru_banner, chrome: ru_chrome, howto: ru_howto, legal: ru_legal, nav: ru_nav, pages: ru_pages, sections: ru_sections, ui: ru_ui, widget: ru_widget },
  sv: { banner: sv_banner, chrome: sv_chrome, nav: sv_nav, pages: sv_pages, sections: sv_sections, ui: sv_ui, widget: sv_widget },
  th: { banner: th_banner, chrome: th_chrome, nav: th_nav, pages: th_pages, sections: th_sections, ui: th_ui, widget: th_widget },
  tr: { banner: tr_banner, chrome: tr_chrome, nav: tr_nav, pages: tr_pages, sections: tr_sections, ui: tr_ui, widget: tr_widget },
  tw: { banner: tw_banner, chrome: tw_chrome, nav: tw_nav, pages: tw_pages, sections: tw_sections, ui: tw_ui, widget: tw_widget },
  ur: { banner: ur_banner, chrome: ur_chrome, nav: ur_nav, pages: ur_pages, sections: ur_sections, ui: ur_ui, widget: ur_widget },
  vi: { banner: vi_banner, chrome: vi_chrome, nav: vi_nav, pages: vi_pages, sections: vi_sections, ui: vi_ui, widget: vi_widget },
};
