/** Regenerates locales/index.ts from the language directories. Run after adding a language: npm run locales:index */
import fs from 'fs';
import path from 'path';

const DIR = path.resolve(process.cwd(), 'locales');
const langs = fs.readdirSync(DIR, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name).sort();
const files = (id: string) => fs.readdirSync(path.join(DIR, id)).filter((f) => f.endsWith('.json')).map((f) => f.replace('.json', ''));

let out = `/* Generated by scripts/build-locale-index.ts – do not edit. One directory per language: locales/<id>/*.json */\n`;
for (const id of langs) for (const f of files(id)) out += `import ${id}_${f} from './${id}/${f}.json';\n`;
out += `\nexport const LOCALE_DATA: Record<string, Record<string, unknown>> = {\n`;
for (const id of langs) out += `  ${id}: { ${files(id).map((f) => `${f}: ${id}_${f}`).join(', ')} },\n`;
out += `};\n`;
fs.writeFileSync(path.join(DIR, 'index.ts'), out);
console.log(`locales/index.ts written for ${langs.length} languages`);
